name: Linting

# This GitHub Action sets up a workflow to perform code linting.
# It triggers on pushes to specific branches and pull requests to master and
# staging branches. It runs on the latest version of Ubuntu. The linting job
# uses different Node versions specified in the matrix to install dependencies
# and lint the code using ESLint.

on:
  push:
    branches:
      - "develop/**"
      - "releases/**"
      - "features/**"
  pull_request:
    branches: ["master", "staging"]
  workflow_dispatch:

jobs:
  linting:
    name: Lint code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
      - name: Code checkout
        uses: actions/checkout@v2

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install modules
        run: npm install

      - name: Lint code
        run: npx eslint . --ext .js,.jsx,.ts,.tsx
