name: Node

# This GitHub Action sets up a workflow to build a Node.js application.
# It triggers on pushes to specific branches and pull requests to master and
# staging branches. It runs on the latest version of Ubuntu. The build job
# uses different Node versions specified in the matrix to install dependencies
# and run the build command.

on:
  push:
    branches:
      - "develop/**"
      - "releases/**"
      - "features/**"
  pull_request:
    branches: ["master", "staging"]
  workflow_dispatch:

jobs:
  build:
    name: Node build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
        env:
          CI: false

      - name: Create build
        run: npm run build --if-present
        env:
          CI: false
