name: Formatting

on:
  push:
    branches:
      - "develop/**"
      - "releases/**"
      - "features/**"
  pull_request:
    branches: ["master", "staging"]
  workflow_dispatch:

jobs:
  prettier:
    name: Format code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{ts,tsx,md}
